name: Convert GHAS data to CSV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
permissions:
  security-events: read

jobs:
  make-csv:
    runs-on: ubuntu-latest
    steps:
      - name: CSV export
        uses: advanced-security/ghas-to-csv@v3
        env:
          GITHUB_PAT: ${{ secrets.PAT }}  # you need to set a PAT
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "ctcampbellcom"
      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: ghas-csv-data
          path: ${{ github.workspace }}/*.csv
          if-no-files-found: error
